export enum localStorageLabels {
  accessToken = 'accessToken',
  assignment = 'assignment',
  client = 'client',
  product = 'product',
  productsPerQuote = 'productsPerQuote',
  productToQuote = 'productToQuote',
  formQuoteGeneral = 'formQuoteGeneral',
  registrationActionCondition = 'registrationActionCondition',
  photo = 'photo',
  quote = 'quote',
  editActionCondition = 'editActionCondition',
  pulledApartData = 'pulledApartData',
  typesOfProductsToQuote = 'typesOfProductsToQuote',
  dataForm = 'dataForm',
  documentType = 'documentType',
  spinning = 'spinning',
}
